server:
  port: 8080
  error:
    include-stacktrace: always
    
spring:
  application:
    name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: f3ac79c641966bee3b01
            client-secret: 0f1da7ba8ff79d6747550da73326da810d096d25
          google:
            client-id: 1030164748087-9c29uokvisqtau3spmhmp4h94lqdf7b7.apps.googleusercontent.com
            client-secret: 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
  data:
    cassandra:
      schema-action: create-if-not-exists

astra:
  api:
    application-token: ${ASTRA_ORG_TOKEN}
    database-id: ${ASTRA_DB_ID}
    database-region: ${ASTRA_DB_REGION}
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DB_KEYSPACE}
      advanced:
        connection:
          init-query-timeout: 10s