name: Astra Cli Sample
on:
  push:
    branches:
      - main
jobs:
  cli-create-db:
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
      ASTRA_DB_KEYSPACE: better_reads
      TERM: linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Astra CLI
        run: curl -Ls "https://dtsx.io/get-astra-cli" | bash
